
const CATS=['PC / Laptop','Server','Router','Switch','Access Point','CCTV','NVR / DVR','Printer','UPS','Monitor','Lainnya'];const STAT=['Aktif','Maintenance','Rusak','Tidak Digunakan'];const COND=['Baik','Cukup','Rusak'];
const seedAssets=[['ast-001','AST-BTG-2024-001','Core Switch Cisco Catalyst 3850','Switch','Cisco','WS-C3850-24T-L','FOC2134S0AB','10.10.1.1','00:1A:2B:3C:4D:5E','Ruang NOC Diskominfo Lt. 2','Baik','Aktif','Switch backbone utama jaringan intra-pemerintah Kabupaten Batang.'],['ast-002','AST-BTG-2024-002','Router Mikrotik CCR1036-8G-2S+','Router','MikroTik','Cloud Core Router CCR1036','4C5E0C881234','10.10.1.254','4C:5E:0C:88:12:34','Ruang Server NOC Lt. 2','Baik','Aktif','Gateway routing internet terpusat OPD Kabupaten Batang.'],['ast-003','AST-BTG-2025-003','Server Dell PowerEdge R740','Server','Dell EMC','PowerEdge R740 Rack 2U','8HQ29Z2','10.10.2.10','D4:BE:D9:11:22:33','Data Center Diskominfo','Baik','Aktif','Host virtualisasi portal web resmi dan layanan publik.'],['ast-004','AST-BTG-2025-004','PC All-in-One HP ProOne 440 G9','PC / Laptop','HP','ProOne 440 G9 AiO 24"','5CD3128790','10.10.3.45','70:85:C2:55:66:77','Ruang Bidang IKP Lt. 1','Baik','Aktif','Komputer operasional produksi konten berita dan media sosial.'],['ast-005','AST-BTG-2025-005','Access Point UniFi U6 Pro','Access Point','Ubiquiti','UniFi 6 Pro','68D79A8899AA','10.10.4.15','68:D7:9A:88:99:AA','Aula Pertemuan Kantor Diskominfo','Cukup','Maintenance','Sedang pengecekan interferensi Wi-Fi dan pembaruan firmware.'],['ast-006','AST-BTG-2025-006','CCTV IP Camera Hikvision Outdoor','CCTV','Hikvision','DS-2CD2043G2-I 4MP','HK20250918','10.10.5.21','AC:CC:8E:10:20:30','Gerbang Masuk Pemkab Batang','Baik','Aktif','Terkoneksi ke Command Center Batang Smart City.'],['ast-007','AST-BTG-2026-007','UPS APC Smart-UPS RT 5000VA','UPS','APC','SRT5KRMXLI Online Rack','AS194820019','10.10.2.250','00:C0:B7:AA:BB:CC','Rack Server Data Center Lt. 2','Baik','Aktif','Backup daya darurat 5kVA untuk rak server utama.'],['ast-008','AST-BTG-2026-008','Printer Laser Multifungsi Canon iR2625i','Printer','Canon','imageRUNNER 2625i','CN2625-8831','10.10.3.90','00:1E:8F:33:44:55','Ruang Sekretariat Diskominfo','Rusak','Rusak','Fuser unit error, menunggu pengadaan suku cadang.']].map(a=>({id:a[0],kodeAset:a[1],nama:a[2],kategori:a[3],merk:a[4],model:a[5],serialNumber:a[6],ipAddress:a[7],macAddress:a[8],lokasi:a[9],kondisi:a[10],status:a[11],keterangan:a[12],fotoUrl:''}));
const seedMaint=[{id:'mnt-001',assetId:'ast-005',tanggal:'2026-03-02',teknisi:'Budi Santoso',keluhan:'Koneksi WiFi sering lambat dan putus saat kapasitas aula penuh.',tindakan:'Cek PoE, kabel LAN dan channel 5GHz.',hasil:'Masih dalam pemantauan.'},{id:'mnt-002',assetId:'ast-008',tanggal:'2026-02-28',teknisi:'Wahyu Pratama',keluhan:'Paper jam dan error fuser.',tindakan:'Pembersihan sensor dan pemeriksaan roller.',hasil:'Menunggu suku cadang.'},{id:'mnt-003',assetId:'ast-001',tanggal:'2026-01-10',teknisi:'Budi Santoso',keluhan:'Perawatan berkala.',tindakan:'Backup konfigurasi dan pembersihan.',hasil:'Kondisi prima.'}];
let assets=[], maint=[], page='dashboard',editing=null,selected=null,search=''; let db=null; const DEMO_SEED_KEY='btg_seeded_v17';
function firebaseReady(){return window.BTG_FIREBASE_CONFIG && window.BTG_FIREBASE_CONFIG.apiKey && !String(window.BTG_FIREBASE_CONFIG.apiKey).includes('ISI_')}
async function initCloud(){
  // Render dulu agar halaman tidak putih saat koneksi Firebase lambat/gagal.
  assets=seedAssets; maint=seedMaint; render();
  if(!firebaseReady()){
    toast('Firebase belum dikonfigurasi. Isi firebase-config.js terlebih dahulu.');
    return;
  }
  try{
    if(!window.firebase || !firebase.initializeApp) throw new Error('Firebase SDK tidak termuat. Periksa koneksi internet.');
    if(!firebase.apps.length) firebase.initializeApp(window.BTG_FIREBASE_CONFIG);
    db=firebase.firestore();
    await Promise.race([
      seedCloudIfEmpty(),
      new Promise((_,reject)=>setTimeout(()=>reject(new Error('Koneksi Firestore terlalu lama.')),10000))
    ]);
    await Promise.race([
      loadCloud(),
      new Promise((_,reject)=>setTimeout(()=>reject(new Error('Pembacaan Firestore terlalu lama.')),10000))
    ]);
    render();
  }catch(err){
    console.error(err);
    db=null;
    assets=seedAssets; maint=seedMaint;
    render();
    toast('Firestore belum tersambung: '+(err.message||'periksa konfigurasi'));
  }
}
async function seedCloudIfEmpty(){ const snap=await db.collection('assets').limit(1).get(); if(snap.empty && !localStorage.getItem(DEMO_SEED_KEY)){ const batch=db.batch(); seedAssets.forEach(a=>batch.set(db.collection('assets').doc(a.id),a)); seedMaint.forEach(m=>batch.set(db.collection('maintenance').doc(m.id),m)); await batch.commit(); localStorage.setItem(DEMO_SEED_KEY,'1'); }}
async function loadCloud(){ const [as,ms]=await Promise.all([db.collection('assets').get(),db.collection('maintenance').get()]); assets=as.docs.map(d=>d.data()); maint=ms.docs.map(d=>d.data()); }

const save=async()=>{ if(!db){return} const batch=db.batch(); assets.forEach(a=>batch.set(db.collection('assets').doc(a.id),a)); maint.forEach(m=>batch.set(db.collection('maintenance').doc(m.id),m)); await batch.commit(); };
async function uploadPhoto(file){ if(!file) return ''; const fd=new FormData(); fd.append('file',file); const r=await fetch('/api/upload',{method:'POST',body:fd}); if(!r.ok) throw new Error(await r.text()); const j=await r.json(); return j.url; }
async function deletePhoto(url){ if(!url || !url.includes('blob.vercel-storage.com')) return; try{await fetch('/api/upload?url='+encodeURIComponent(url),{method:'DELETE'});}catch(e){console.warn(e)} }const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));const mapUrl=l=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(l);const toast=m=>{let t=document.createElement('div');t.className='toast';t.textContent=m;document.body.appendChild(t);setTimeout(()=>t.remove(),2400)};
function logo(src,cls=''){return `<img class="${cls}" src="${src}" onclick="openLogo('${src}')" alt="Logo">`}function openLogo(src){document.getElementById('modal').innerHTML=`<div class="modal logo-modal"><button class="close" onclick="closeModal()">×</button><div style="margin-top:10px">${logo(src,'preview-logo')}</div></div>`;document.getElementById('modalBack').classList.remove('hidden')};function closeModal(){document.getElementById('modalBack').classList.add('hidden');document.getElementById('modal').innerHTML=''}
function login(){document.getElementById('root').innerHTML=`<main class="login"><section class="login-card"><div class="login-logos">${logo('assets/pemkab-batang.png','login-logo')}${logo('assets/diskominfo-batang.jpg','login-logo disk')}</div><h1>IT Asset Management</h1><p>Diskominfo Kabupaten Batang</p><form onsubmit="doLogin(event)"><div class="field"><label>Username</label><input id="u" autocomplete="username" required></div><div class="field"><label>Password</label><div class="password-wrap"><input id="p" type="password" autocomplete="current-password" required><button type="button" class="eye" onclick="togglePass()">◉</button></div></div><div class="login-error" id="err"></div><button class="btn primary" style="width:100%">Masuk</button></form></section></main>`}
function doLogin(e){e.preventDefault();if(document.getElementById('u').value==='admin'&&document.getElementById('p').value==='kominfobatang'){sessionStorage.setItem('btg_login','1');render()}else document.getElementById('err').textContent='Username atau password salah.'}function togglePass(){let p=document.getElementById('p');p.type=p.type==='password'?'text':'password'}function logout(){sessionStorage.removeItem('btg_login');login()}
function render(){if(!sessionStorage.getItem('btg_login'))return login();let content=page==='dashboard'?dashboard():page==='assets'?inventory():page==='maintenance'?maintenance():page==='reports'?reports():monitoring();document.getElementById('root').innerHTML=`<div class="app"><aside class="sidebar"><div class="brand">${logo('assets/pemkab-batang.png','brand-main')}<h2>IT Asset Management</h2><small>Diskominfo Batang</small>${logo('assets/diskominfo-batang.jpg','mini-logo')}</div><nav class="nav"><button class="${page==='dashboard'?'active':''}" onclick="go('dashboard')">▦ <span>Dashboard</span></button><button class="${page==='assets'?'active':''}" onclick="go('assets')">▣ <span>Data Aset</span></button><button class="${page==='maintenance'?'active':''}" onclick="go('maintenance')">⚒ <span>Maintenance</span></button><button class="${page==='monitoring'?'active':''}" onclick="go('monitoring')">◉ <span>Monitoring</span></button><button class="${page==='reports'?'active':''}" onclick="go('reports')">▤ <span>Laporan</span></button></nav><div class="side-bottom"><button class="btn danger" style="width:100%" onclick="logout()">Keluar <span>↪</span></button></div></aside><main class="main"><div class="page"><header class="topbar"><div><h1>${pageTitle()}</h1><p>Pengelolaan aset teknologi informasi Diskominfo Kabupaten Batang</p></div><div class="top-actions"><button class="btn" onclick="go('monitoring')">Monitoring</button><button class="btn primary" onclick="openForm()">+ Tambah Aset</button></div></header>${content}</div></main></div><div id="modalBack" class="modal-back hidden" onclick="if(event.target===this)closeModal()"><div id="modal"></div></div>`}function pageTitle(){return ({dashboard:'Dashboard',assets:'Data Aset',maintenance:'Maintenance',monitoring:'Monitoring Perangkat',reports:'Laporan'})[page]}
function go(p){page=p;render()}function counts(){return{total:assets.length,active:assets.filter(a=>a.status==='Aktif').length,maint:assets.filter(a=>a.status==='Maintenance').length,broken:assets.filter(a=>a.status==='Rusak').length}}
function dashboard(){let c=counts();return `<div class="cards"><div class="card stat"><span>Total Aset</span><b>${c.total}</b></div><div class="card stat"><span>Aktif</span><b>${c.active}</b></div><div class="card stat"><span>Maintenance</span><b>${c.maint}</b></div><div class="card stat"><span>Rusak</span><b>${c.broken}</b></div></div><div class="grid2 section"><div class="card"><div class="section-head"><h2>Aset Terbaru</h2><button class="btn" onclick="go('assets')">Lihat semua</button></div>${assets.slice(-5).reverse().map(assetRow).join('')}</div><div class="card"><div class="section-head"><h2>Deteksi Kondisi</h2><button class="btn" onclick="go('monitoring')">Detail</button></div>${alerts().slice(0,5).map(a=>`<div style="padding:10px 0;border-bottom:1px solid var(--line)"><b>${esc(a.nama)}</b><div style="color:var(--muted);font-size:13px">${esc(a.reason)}</div></div>`).join('')||'<p style="color:var(--muted)">Tidak ada indikator masalah.</p>'}</div></div>`}function assetRow(a){return `<div style="padding:11px 0;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;gap:10px"><div><b>${esc(a.nama)}</b><div style="font-size:12px;color:var(--muted)">${esc(a.kodeAset)} · ${esc(a.lokasi)}</div></div>${chip(a.status)}</div>`}function chip(s){return `<span class="chip ${s==='Aktif'?'ok':s==='Rusak'?'bad':'warn'}">${esc(s)}</span>`}
function inventory(){let list=assets.filter(a=>JSON.stringify(a).toLowerCase().includes(search.toLowerCase()));return `<div class="card"><div class="section-head"><h2>${list.length} perangkat</h2><div class="tools"><input class="field search" style="margin:0" placeholder="Cari aset, IP, lokasi..." value="${esc(search)}" oninput="search=this.value;render()"><select onchange="sortAssets(this.value)" class="btn"><option value="">Urutkan</option><option value="name">Nama A-Z</option><option value="code">Kode aset</option></select></div></div><div class="asset-grid">${list.map(a=>`<article class="asset-card">${a.fotoUrl?`<img src="${a.fotoUrl}" class="detail-photo">`:''}<h3>${esc(a.nama)}</h3><p><b>${esc(a.kodeAset)}</b></p><p>${esc(a.kategori)} · ${esc(a.merk)}</p><p>${esc(a.lokasi)}</p><p>${chip(a.status)} ${chip(a.kondisi)}</p><div class="actions"><button class="btn" onclick="detail('${a.id}')">Detail</button><button class="btn" onclick="openForm('${a.id}')">Edit</button><button class="btn" onclick="window.open('${mapUrl(a.lokasi)}','_blank')">Maps</button><button class="btn danger" onclick="removeAsset('${a.id}')">Hapus</button></div></article>`).join('')||'<p>Tidak ada aset.</p>'}</div></div>`}function sortAssets(v){if(v==='name')assets.sort((a,b)=>a.nama.localeCompare(b.nama));if(v==='code')assets.sort((a,b)=>a.kodeAset.localeCompare(b.kodeAset));save();render()}
function openForm(id){editing=id||null;let a=id?assets.find(x=>x.id===id):{kodeAset:'',nama:'',kategori:CATS[0],merk:'',model:'',serialNumber:'',ipAddress:'',macAddress:'',lokasi:'',kondisi:'Baik',status:'Aktif',keterangan:'',fotoUrl:''};document.getElementById('modal').innerHTML=`<div class="modal"><div class="modal-head"><h2>${id?'Edit Aset':'Tambah Aset'}</h2><button class="close" onclick="closeModal()">×</button></div><form onsubmit="saveAsset(event)" class="form-grid"><div class="field"><label>Kode Aset</label><input name="kodeAset" value="${esc(a.kodeAset)}" required></div><div class="field"><label>Nama Perangkat</label><input name="nama" value="${esc(a.nama)}" required></div><div class="field"><label>Kategori</label><select name="kategori">${CATS.map(x=>`<option ${x===a.kategori?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Merk</label><input name="merk" value="${esc(a.merk)}"></div><div class="field"><label>Model</label><input name="model" value="${esc(a.model)}"></div><div class="field"><label>Serial Number</label><input name="serialNumber" value="${esc(a.serialNumber)}"></div><div class="field"><label>IP Address</label><input name="ipAddress" value="${esc(a.ipAddress)}"></div><div class="field"><label>MAC Address</label><input name="macAddress" value="${esc(a.macAddress)}"></div><div class="field"><label>Lokasi</label><input name="lokasi" value="${esc(a.lokasi)}" required></div><div class="field"><label>Kondisi</label><select name="kondisi">${COND.map(x=>`<option ${x===a.kondisi?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Status</label><select name="status">${STAT.map(x=>`<option ${x===a.status?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Foto Aset</label><input name="foto" type="file" accept="image/*"><input type="hidden" name="fotoUrl" value="${esc(a.fotoUrl)}"></div><div class="field full"><label>Keterangan</label><textarea name="keterangan">${esc(a.keterangan)}</textarea></div><div class="form-actions full"><button type="button" class="btn" onclick="closeModal()">Batal</button><button class="btn primary">Simpan</button></div></form></div>`;document.getElementById('modalBack').classList.remove('hidden')}
async function saveAsset(e){e.preventDefault();let f=new FormData(e.target),data=Object.fromEntries(f.entries());let file=e.target.foto.files[0];try{ if(file) data.fotoUrl=await uploadPhoto(file); else data.fotoUrl=data.fotoUrl||''; delete data.foto; if(editing){let old=assets.find(a=>a.id===editing); if(old && old.fotoUrl && old.fotoUrl!==data.fotoUrl) await deletePhoto(old.fotoUrl); Object.assign(old,data)}else assets.push({id:'ast-'+Date.now(),...data}); await save(); closeModal(); toast('Aset berhasil disimpan ke Firestore'); await loadCloud(); render(); }catch(err){console.error(err);toast('Gagal menyimpan: '+(err.message||err));}}
async function removeAsset(id){if(confirm('Hapus aset ini?')){let old=assets.find(a=>a.id===id); assets=assets.filter(a=>a.id!==id);maint=maint.filter(m=>m.assetId!==id);try{if(old?.fotoUrl) await deletePhoto(old.fotoUrl); if(db){await db.collection('assets').doc(id).delete(); let q=await db.collection('maintenance').where('assetId','==',id).get(); let b=db.batch(); q.forEach(d=>b.delete(d.ref)); await b.commit();}toast('Aset dihapus');await loadCloud();render()}catch(e){toast('Gagal menghapus: '+e.message)}}}function detail(id){let a=assets.find(x=>x.id===id),ms=maint.filter(m=>m.assetId===id);document.getElementById('modal').innerHTML=`<div class="modal"><div class="modal-head"><h2>${esc(a.nama)}</h2><button class="close" onclick="closeModal()">×</button></div>${a.fotoUrl?`<img src="${a.fotoUrl}" class="detail-photo">`:''}<div class="kv"><div>Kode</div><div>${esc(a.kodeAset)}</div><div>Kategori</div><div>${esc(a.kategori)}</div><div>Merk/Model</div><div>${esc(a.merk)} / ${esc(a.model)}</div><div>Serial</div><div>${esc(a.serialNumber)}</div><div>IP / MAC</div><div>${esc(a.ipAddress)} / ${esc(a.macAddress)}</div><div>Lokasi</div><div>${esc(a.lokasi)} <button class="btn" onclick="window.open('${mapUrl(a.lokasi)}','_blank')">Buka Google Maps</button></div><div>Kondisi</div><div>${chip(a.kondisi)}</div><div>Status</div><div>${chip(a.status)}</div><div>Keterangan</div><div>${esc(a.keterangan)}</div></div><hr><h3>Riwayat Maintenance</h3>${ms.map(m=>`<div class="card" style="box-shadow:none;padding:12px;margin:8px 0"><b>${esc(m.tanggal)} — ${esc(m.teknisi)}</b><p>${esc(m.keluhan)}</p><p>${esc(m.tindakan)}</p><small>${esc(m.hasil)}</small></div>`).join('')||'<p style="color:var(--muted)">Belum ada riwayat.</p>'}<div class="form-actions"><button class="btn" onclick="openMaint('${a.id}')">Tambah Maintenance</button><button class="btn" onclick="printLabel('${a.id}')">Cetak Label</button><button class="btn primary" onclick="openForm('${a.id}')">Edit</button></div></div>`;document.getElementById('modalBack').classList.remove('hidden')}
function openMaint(id){let a=assets.find(x=>x.id===id);document.getElementById('modal').innerHTML=`<div class="modal"><div class="modal-head"><h2>Tambah Maintenance</h2><button class="close" onclick="closeModal()">×</button></div><form onsubmit="saveMaint(event,'${id}')"><div class="field"><label>Tanggal</label><input name="tanggal" type="date" value="${new Date().toISOString().slice(0,10)}" required></div><div class="field"><label>Teknisi</label><input name="teknisi" required></div><div class="field"><label>Keluhan</label><textarea name="keluhan" required></textarea></div><div class="field"><label>Tindakan</label><textarea name="tindakan" required></textarea></div><div class="field"><label>Hasil</label><textarea name="hasil"></textarea></div><div class="field"><label>Status aset</label><select name="status">${STAT.map(s=>`<option ${s===a.status?'selected':''}>${s}</option>`).join('')}</select></div><div class="form-actions"><button type="button" class="btn" onclick="detail('${id}')">Batal</button><button class="btn primary">Simpan</button></div></form></div>`;document.getElementById('modalBack').classList.remove('hidden')}
async function saveMaint(e,id){e.preventDefault();let d=Object.fromEntries(new FormData(e.target));let m={id:'mnt-'+Date.now(),assetId:id,...d};maint.unshift(m);assets.find(a=>a.id===id).status=d.status;try{if(db){await db.collection('maintenance').doc(m.id).set(m);await db.collection('assets').doc(id).update({status:d.status});}closeModal();toast('Maintenance tersimpan');await loadCloud();render()}catch(e){toast('Gagal menyimpan maintenance: '+e.message)}}
function maintenance(){return `<div class="card"><div class="section-head"><h2>Riwayat Maintenance</h2></div><div class="table-wrap"><table class="table"><thead><tr><th>Tanggal</th><th>Aset</th><th>Teknisi</th><th>Keluhan</th><th>Tindakan</th><th>Hapus</th></tr></thead><tbody>${maint.map(m=>{let a=assets.find(x=>x.id===m.assetId);return `<tr><td>${esc(m.tanggal)}</td><td>${esc(a?.nama||'-')}</td><td>${esc(m.teknisi)}</td><td>${esc(m.keluhan)}</td><td>${esc(m.tindakan)}</td><td><button class="btn danger" onclick="delMaint('${m.id}')">Hapus</button></td></tr>`}).join('')}</tbody></table></div></div>`}async function delMaint(id){if(confirm('Hapus riwayat maintenance?')){maint=maint.filter(m=>m.id!==id);try{if(db)await db.collection('maintenance').doc(id).delete();toast('Riwayat dihapus');await loadCloud();render()}catch(e){toast('Gagal menghapus: '+e.message)}}}
function alerts(){return assets.flatMap(a=>{let r=[];if(a.status==='Rusak'||a.kondisi==='Rusak')r.push({nama:a.nama,reason:'Perangkat berstatus rusak dan perlu penanganan.',level:'danger'});else if(a.status==='Maintenance')r.push({nama:a.nama,reason:'Sedang dalam maintenance/pemantauan.',level:'warn'});if(!a.ipAddress)r.push({nama:a.nama,reason:'IP address belum terdaftar.',level:'warn'});let repeat=maint.filter(m=>m.assetId===a.id).length;if(repeat>=2)r.push({nama:a.nama,reason:`Memiliki ${repeat} riwayat maintenance; perlu perhatian.`,level:'warn'});return r})}function monitoring(){let al=alerts();return `<div class="cards"><div class="card stat"><span>Indikator Terdeteksi</span><b>${al.length}</b></div><div class="card stat"><span>Perangkat Rusak</span><b>${assets.filter(a=>a.status==='Rusak').length}</b></div><div class="card stat"><span>Maintenance</span><b>${assets.filter(a=>a.status==='Maintenance').length}</b></div><div class="card stat"><span>IP Kosong</span><b>${assets.filter(a=>!a.ipAddress).length}</b></div></div><div class="card section"><h2>Smart Monitoring</h2><p style="color:var(--muted)">Deteksi otomatis berbasis data aset. Ini adalah pondasi untuk integrasi ping/SNMP dan AI pada tahap berikutnya.</p>${al.map(x=>`<div class="card monitor ${x.level==='danger'?'danger':'alert'}" style="box-shadow:none;margin:10px 0"><b>${esc(x.nama)}</b><div>${esc(x.reason)}</div></div>`).join('')||'<p>Tidak ada indikator trouble saat ini.</p>'}</div>`}
function reports(){return `<div class="card"><div class="section-head"><h2>Laporan Aset</h2><div class="tools"><button class="btn" onclick="exportCSV()">Export CSV</button><button class="btn primary" onclick="window.print()">Cetak</button></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Kode</th><th>Nama</th><th>Kategori</th><th>Lokasi</th><th>Kondisi</th><th>Status</th></tr></thead><tbody>${assets.map(a=>`<tr><td>${esc(a.kodeAset)}</td><td>${esc(a.nama)}</td><td>${esc(a.kategori)}</td><td>${esc(a.lokasi)}</td><td>${chip(a.kondisi)}</td><td>${chip(a.status)}</td></tr>`).join('')}</tbody></table></div></div>`}function exportCSV(){let rows=[['Kode Aset','Nama','Kategori','Merk','Model','Serial','IP','MAC','Lokasi','Kondisi','Status','Keterangan'],...assets.map(a=>[a.kodeAset,a.nama,a.kategori,a.merk,a.model,a.serialNumber,a.ipAddress,a.macAddress,a.lokasi,a.kondisi,a.status,a.keterangan])];let csv=rows.map(r=>r.map(x=>'"'+String(x??'').replaceAll('"','""')+'"').join(',')).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='laporan-aset-diskominfo-batang.csv';a.click();URL.revokeObjectURL(a.href)}function printLabel(id){let a=assets.find(x=>x.id===id);if(!a)return;let w=window.open('','_blank');if(!w){toast('Popup diblokir browser. Izinkan popup untuk mencetak label.');return;}w.document.write(`<html><head><title>Label ${esc(a.kodeAset)}</title><style>body{font-family:Arial;padding:30px;text-align:center}.box{border:2px solid #222;padding:20px;width:350px;margin:auto}img{max-width:100px;height:80px;object-fit:contain}</style></head><body><div class="box"><img src="assets/pemkab-batang.png"><h2>${esc(a.nama)}</h2><b>${esc(a.kodeAset)}</b><p>${esc(a.lokasi)}</p><p>${esc(a.ipAddress)}</p><p>Scan/identifikasi: ${esc(a.kodeAset)}</p></div><\/body><\/html>`);w.document.close();setTimeout(()=>{w.focus();w.print();},250)}
initCloud();
