import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {QRCodeSVG} from 'qrcode.react';
import {collection,addDoc,deleteDoc,doc,onSnapshot,serverTimestamp,query,orderBy} from 'firebase/firestore';
import {db} from './firebase';
import './style.css';

const cats=['PC / Laptop','Router','Switch','Access Point','CCTV','NVR / DVR','Printer','Server','UPS','Monitor','Lainnya'];
const statuses=['Aktif','Maintenance','Rusak','Tidak Digunakan'];
const empty={kodeAset:'',nama:'',kategori:'PC / Laptop',merk:'',model:'',serialNumber:'',ipAddress:'',macAddress:'',lokasi:'',kondisi:'Baik',status:'Aktif',keterangan:'',fotoUrl:''};

function App(){
 const [assets,setAssets]=useState([]),[maint,setMaint]=useState([]),[page,setPage]=useState('dashboard'),[search,setSearch]=useState(''),[filter,setFilter]=useState('Semua'),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[selected,setSelected]=useState(null),[login,setLogin]=useState(false),[email,setEmail]=useState(''),[pass,setPass]=useState(''),[showPass,setShowPass]=useState(false),[loading,setLoading]=useState(false);
 useEffect(()=>onSnapshot(query(collection(db,'assets'),orderBy('createdAt','desc')),s=>setAssets(s.docs.map(d=>({id:d.id,...d.data()}))),()=>setAssets([])),[]);
 useEffect(()=>onSnapshot(query(collection(db,'maintenance'),orderBy('tanggal','desc')),s=>setMaint(s.docs.map(d=>({id:d.id,...d.data()}))),()=>setMaint([])),[]);
 const counts={total:assets.length,aktif:assets.filter(x=>x.status==='Aktif').length,maint:assets.filter(x=>x.status==='Maintenance').length,rusak:assets.filter(x=>x.status==='Rusak').length};
 const visible=assets.filter(x=>(filter==='Semua'||x.status===filter)&&(Object.values(x).join(' ').toLowerCase().includes(search.toLowerCase())));
 function openAdd(){setForm({...empty,kodeAset:'AST-'+String(Date.now()).slice(-5)});setEditing(null);setPage('form')}
 function openEdit(a){setForm({...empty,...a});setEditing(a.id);setPage('form')}
 async function save(e){e.preventDefault();setLoading(true);try{
   let foto=form.fotoUrl;
   const payload={...form,fotoUrl:foto,updatedAt:serverTimestamp()};
   if(editing) await import('firebase/firestore').then(({updateDoc})=>updateDoc(doc(db,'assets',editing),payload));
   else await addDoc(collection(db,'assets'),{...payload,createdAt:serverTimestamp()});
   setPage('inventaris');setForm(empty);setEditing(null);
 }catch(err){alert('Gagal menyimpan: '+err.message)}finally{setLoading(false)}}
 async function remove(id){if(confirm('Hapus perangkat ini?')) await deleteDoc(doc(db,'assets',id));}
 async function addMaintenance(e){e.preventDefault();const f=new FormData(e.currentTarget);await addDoc(collection(db,'maintenance'),{assetId:selected.id,tanggal:f.get('tanggal'),teknisi:f.get('teknisi'),keluhan:f.get('keluhan'),tindakan:f.get('tindakan'),hasil:f.get('hasil'),createdAt:serverTimestamp()});e.currentTarget.reset();alert('Riwayat maintenance tersimpan')}
 if(!login)return <Login email={email} pass={pass} setEmail={setEmail} setPass={setPass} showPass={showPass} setShowPass={setShowPass} enter={()=>{if(email==='admin'&&pass==='kominfobatang')setLogin(true);else alert('Username atau password salah')}}/>;
 return <div className="app"><aside><div className="brand"><div className="logo">IT</div><div><b>IT Asset</b><span>Management</span></div></div>
  {['dashboard','inventaris','maintenance','laporan'].map(p=><button className={page===p?'nav active':'nav'} onClick={()=>setPage(p)} key={p}>{({dashboard:'Dashboard',inventaris:'Inventaris',maintenance:'Maintenance',laporan:'Laporan'})[p]}</button>)}
  <button className="nav logout" onClick={()=>setLogin(false)}>Keluar</button>
 </aside><main><header><div><h1>{page==='dashboard'?'Dashboard':page[0].toUpperCase()+page.slice(1)}</h1><p>Kelola perangkat dan aset IT tempat magang.</p></div><button className="primary" onClick={openAdd}>+ Tambah Perangkat</button></header>
 {page==='dashboard'&&<Dashboard counts={counts} assets={assets} setSelected={setSelected} setPage={setPage}/>}
 {page==='inventaris'&&<><div className="toolbar"><input placeholder="Cari kode, nama, lokasi, IP..." value={search} onChange={e=>setSearch(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option>Semua</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></div><div className="grid">{visible.map(a=><AssetCard key={a.id} a={a} onEdit={()=>openEdit(a)} onDelete={()=>remove(a.id)} onOpen={()=>setSelected(a)}/>)}{!visible.length&&<div className="empty">Belum ada perangkat.</div>}</div></>}
 {page==='form'&&<AssetForm form={form} setForm={setForm} save={save} loading={loading} editing={editing} cancel={()=>setPage('inventaris')}/>}
 {page==='maintenance'&&<Maintenance assets={assets} maint={maint} selected={selected} setSelected={setSelected} addMaintenance={addMaintenance}/>}
 {page==='laporan'&&<Reports assets={assets}/>}
 {selected&&<Detail a={selected} maint={maint.filter(m=>m.assetId===selected.id)} close={()=>setSelected(null)} addMaintenance={addMaintenance}/>}
 </main></div>
}

function EyeIcon({open}){return open?<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M2.5 12s3.4-6 9.5-6 9.5 6 9.5 6-3.4 6-9.5 6-9.5-6-9.5-6Z"/><circle cx="12" cy="12" r="2.7"/></svg>:<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="m3 3 18 18"/><path d="M10.6 6.2C11.05 6.07 11.52 6 12 6c6.1 0 9.5 6 9.5 6a16.8 16.8 0 0 1-3.1 3.7"/><path d="M6.2 6.9C3.8 8.3 2.5 12 2.5 12s3.4 6 9.5 6c1.15 0 2.2-.2 3.15-.52"/><path d="M9.9 9.9a2.7 2.7 0 0 0 3.8 3.8"/></svg>}
function Login(p){return <div className="login"><div className="loginbox"><div className="logo big">IT</div><h1>IT Asset Management</h1><p>Panel Administrasi Perangkat & Aset IT</p><input placeholder="Username" autoComplete="username" value={p.email} onChange={e=>p.setEmail(e.target.value)}/><div className="password"><input type={p.showPass?'text':'password'} placeholder="Password" autoComplete="current-password" value={p.pass} onChange={e=>p.setPass(e.target.value)} onKeyDown={e=>e.key==='Enter'&&p.enter()}/><button aria-label={p.showPass?'Sembunyikan password':'Tampilkan password'} title={p.showPass?'Sembunyikan password':'Tampilkan password'} onClick={()=>p.setShowPass(!p.showPass)}><EyeIcon open={p.showPass}/></button></div><button className="primary full" onClick={p.enter}>Masuk ke Sistem</button><small>© 2026 · Sistem Manajemen Aset IT</small></div></div>}

function Dashboard({counts,assets,setSelected,setPage}){return <><div className="stats">{[['Total Perangkat',counts.total],['Aktif',counts.aktif],['Maintenance',counts.maint],['Rusak',counts.rusak]].map(x=><div className="stat" key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong></div>)}</div><section className="panel"><div className="panelhead"><h2>Perangkat Terbaru</h2><button onClick={()=>setPage('inventaris')}>Lihat semua</button></div>{assets.slice(0,6).map(a=><div className="row" key={a.id} onClick={()=>setSelected(a)}><div className="thumb">{a.fotoUrl?<img src={a.fotoUrl}/>:a.kategori?.slice(0,2)}</div><div><b>{a.nama}</b><span>{a.kodeAset} · {a.lokasi||'Lokasi belum diisi'}</span></div><Status s={a.status}/></div>)}</section></>}

function Status({s}){return <span className={'status '+s.toLowerCase().replaceAll(' ','-')}>{s}</span>}
function AssetCard({a,onEdit,onDelete,onOpen}){return <div className="card"><div className="photo">{a.fotoUrl?<img src={a.fotoUrl}/>:<span>{a.kategori?.slice(0,3)}</span>}</div><div className="cardbody"><div className="between"><b>{a.nama||'Tanpa nama'}</b><Status s={a.status}/></div><span className="muted">{a.kodeAset} · {a.kategori}</span><p>{a.lokasi||'Lokasi belum diisi'}</p><div className="actions"><button onClick={onOpen}>Detail</button><button onClick={onEdit}>Edit</button><button className="danger" onClick={onDelete}>Hapus</button></div></div></div>}

function AssetForm({form,setForm,save,loading,editing,cancel}){const [upload,setUpload]=useState(false);async function blob(e){const file=e.target.files[0];if(!file)return;setUpload(true);try{const r=await fetch('/api/upload',{method:'POST',headers:{'content-type':file.type},body:file});if(!r.ok)throw Error('Upload gagal');const d=await r.json();setForm({...form,fotoUrl:d.url})}catch(e){alert(e.message)}finally{setUpload(false)}}return <form className="form panel" onSubmit={save}><div className="formgrid">{Object.entries({kodeAset:'Kode Aset',nama:'Nama Perangkat',merk:'Merk',model:'Model',serialNumber:'Serial Number',ipAddress:'IP Address',macAddress:'MAC Address',lokasi:'Lokasi'}).map(([k,l])=><label key={k}>{l}<input required={['kodeAset','nama'].includes(k)} value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label>Kategori<select value={form.kategori} onChange={e=>setForm({...form,kategori:e.target.value})}>{cats.map(c=><option key={c}>{c}</option>)}</select></label><label>Kondisi<select value={form.kondisi} onChange={e=>setForm({...form,kondisi:e.target.value})}><option>Baik</option><option>Cukup</option><option>Rusak</option></select></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label className="wide">Foto Perangkat<input type="file" accept="image/*" onChange={blob}/>{upload&&<small>Mengunggah ke Vercel Blob...</small>}{form.fotoUrl&&<img className="preview" src={form.fotoUrl}/>}</label><label className="wide">Keterangan<textarea value={form.keterangan||''} onChange={e=>setForm({...form,keterangan:e.target.value})}/></label></div><div className="formactions"><button type="button" onClick={cancel}>Batal</button><button className="primary" disabled={loading||upload}>{loading?'Menyimpan...':editing?'Simpan Perubahan':'Simpan Perangkat'}</button></div></form>}

function Detail({a,maint,close,addMaintenance}){return <div className="modal"><div className="modalbox"><button className="close" onClick={close}>×</button><div className="detailtop">{a.fotoUrl?<img src={a.fotoUrl}/>:<div className="photo bigphoto">{a.kategori}</div>}<div><h2>{a.nama}</h2><p>{a.kodeAset}</p><Status s={a.status}/></div></div><div className="details">{[['Kategori',a.kategori],['Merk / Model',[a.merk,a.model].filter(Boolean).join(' ')],['Serial Number',a.serialNumber],['IP Address',a.ipAddress],['MAC Address',a.macAddress],['Lokasi',a.lokasi],['Kondisi',a.kondisi]].map(x=><div><span>{x[0]}</span><b>{x[1]||'-'}</b></div>)}</div><h3>Riwayat Maintenance</h3>{maint.map(m=><div className="maintrow"><b>{m.tanggal} · {m.teknisi}</b><span>{m.tindakan||m.keluhan}</span></div>)}<form onSubmit={addMaintenance} className="mini"><input name="tanggal" type="date" required/><input name="teknisi" placeholder="Teknisi" required/><textarea name="keluhan" placeholder="Keluhan"/><textarea name="tindakan" placeholder="Tindakan"/><input name="hasil" placeholder="Hasil"/><button className="primary">Tambah Maintenance</button></form><div className="qr"><QRCodeSVG value={location.origin+'/asset/'+a.id} size={150}/><span>Scan untuk detail aset</span></div></div></div>}

function Maintenance({assets,maint,selected,setSelected,addMaintenance}){return <section className="panel"><h2>Maintenance</h2><select value={selected?.id||''} onChange={e=>setSelected(assets.find(a=>a.id===e.target.value)||null)}><option value="">Pilih perangkat...</option>{assets.map(a=><option value={a.id} key={a.id}>{a.kodeAset} - {a.nama}</option>)}</select>{selected?<form onSubmit={addMaintenance} className="mini"><input name="tanggal" type="date" required/><input name="teknisi" placeholder="Teknisi" required/><textarea name="keluhan" placeholder="Keluhan"/><textarea name="tindakan" placeholder="Tindakan"/><input name="hasil" placeholder="Hasil"/><button className="primary">Simpan Riwayat</button></form>:<p className="empty">Pilih perangkat untuk menambah maintenance.</p>}<h3>Riwayat</h3>{maint.map(m=><div className="maintrow"><b>{m.tanggal} · {m.teknisi}</b><span>{assets.find(a=>a.id===m.assetId)?.nama||'Perangkat dihapus'} — {m.hasil||m.tindakan||m.keluhan}</span></div>)}</section>}
function Reports({assets}){return <section className="panel"><div className="panelhead"><h2>Laporan Inventaris</h2><button onClick={()=>window.print()}>Cetak / Simpan PDF</button></div><table><thead><tr><th>Kode</th><th>Perangkat</th><th>Kategori</th><th>Lokasi</th><th>Status</th><th>Kondisi</th></tr></thead><tbody>{assets.map(a=><tr><td>{a.kodeAset}</td><td>{a.nama}</td><td>{a.kategori}</td><td>{a.lokasi}</td><td>{a.status}</td><td>{a.kondisi}</td></tr>)}</tbody></table></section>}
createRoot(document.getElementById('root')).render(<App/>);